#pragma once

#include "axyb/linear_solver.hpp"

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <random>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace axyb{
struct CommonCli{int len=30,iters=1000;double noise=5e-2,mu=5e-9,retry_tol=0;unsigned long long seed=0;bool seed_set=false,retry_tol_set=false,help=false;SolverOptions solver;};
inline void print_common_help(const char*exe,bool loop){std::cout<<"Usage: "<<exe<<" [options]\n\n"<<"  --backend NAME       "<<backend_help()<<"\n"<<"  --data-dir DIR       template directory; default is executable_dir/templates\n"<<"  --template SEL       use one template or inclusive range (x3 or x2-x4)\n"<<"  --templates A-B      alias for inclusive template range selection\n"<<"  --threads N          limit oneTBB workers\n"<<"  --len N              motion pairs, default 5\n"<<"  --noise X            default 5e-2\n"<<"  --mu X               default 5e-9\n"<<"  --retry_tol X        retry other backends if objective > X\n"<<"  --seed N             reproducible seed\n";if(loop)std::cout<<"  --iters N            loop iterations, default 1000\n";std::cout<<"  --pcg-tol X          default 1e-8\n"<<"  --pcg-maxit N        default 300\n"<<"  --no-fallback        disable direct fallback\n"<<"  --no-template-parallel disable oneTBB across selected templates\n"<<"  --no-backend-parallel disable oneTBB across retry backends\n"<<"  --help\n";}
inline std::string join_path(const std::string&a,const std::string&b){if(a.empty())return b;char c=a.back();return (c=='/'||c=='\\')?a+b:a+"/"+b;}
inline std::string executable_dir(const char*argv0){std::string s=argv0?argv0:"";auto p=s.find_last_of("/\\");if(p==std::string::npos)return ".";if(p==0)return s.substr(0,1);return s.substr(0,p);}
inline bool has_templates(const std::string&dir){std::ifstream f(join_path(dir,"AXYB_complete_x1.tpl"),std::ios::binary);return (bool)f;}
inline int parse_template_index(std::string s,const char*option,const std::string&value){const std::string prefix="AXYB_complete_x";const std::string suffix=".tpl";if(s.size()>=prefix.size()&&s.compare(0,prefix.size(),prefix)==0)s.erase(0,prefix.size());if(s.size()>=suffix.size()&&s.compare(s.size()-suffix.size(),suffix.size(),suffix)==0)s.erase(s.size()-suffix.size());if(!s.empty()&&(s[0]=='x'||s[0]=='X'))s.erase(0,1);if(s.empty()||!std::all_of(s.begin(),s.end(),[](unsigned char ch){return ch>='0'&&ch<='9';}))throw std::runtime_error(std::string("invalid ")+option+" value '"+value+"'; expected x3, 3, x2-x4, or 2-4");int action=std::stoi(s);if(action<1||action>6)throw std::runtime_error(std::string("invalid ")+option+" value '"+value+"'; expected template indices in 1..6");return action;}
inline std::pair<int,int> parse_template_selector(const std::string&value,const char*option){auto dash=value.find('-');if(dash==std::string::npos){int action=parse_template_index(value,option,value);return{action,action};}if(value.find('-',dash+1)!=std::string::npos)throw std::runtime_error(std::string("invalid ")+option+" value '"+value+"'; expected a single inclusive range such as 2-4 or x2-x4");int first=parse_template_index(value.substr(0,dash),option,value);int last=parse_template_index(value.substr(dash+1),option,value);if(first>last)throw std::runtime_error(std::string("invalid ")+option+" value '"+value+"'; expected A-B with A <= B");return{first,last};}
inline CommonCli parse_common_cli(int argc,char**argv,bool loop){CommonCli c;c.solver.backend=parse_backend("tbb-pcg");bool data_dir_set=false;for(int i=1;i<argc;++i){std::string a=argv[i];auto val=[&](const char*n){if(i+1>=argc)throw std::runtime_error(std::string("missing ")+n);return std::string(argv[++i]);};if(a=="--help"||a=="-h")c.help=true;else if(a=="--backend"){c.solver.backend_name=val("--backend");c.solver.backend=parse_backend(c.solver.backend_name);}else if(a=="--data-dir"){c.solver.template_dir=val("--data-dir");data_dir_set=true;}else if(a=="--template"||a=="--templates"){auto range=parse_template_selector(val(a.c_str()),a.c_str());c.solver.template_first=range.first;c.solver.template_last=range.second;}else if(a=="--threads")c.solver.threads=std::stoi(val("--threads"));else if(a=="--len")c.len=std::stoi(val("--len"));else if(a=="--noise")c.noise=std::stod(val("--noise"));else if(a=="--mu")c.mu=std::stod(val("--mu"));else if(a=="--retry_tol"){c.retry_tol=std::stod(val("--retry_tol"));if(c.retry_tol<0)throw std::runtime_error("--retry_tol must be >= 0");c.retry_tol_set=true;}else if(a=="--seed"){c.seed=std::stoull(val("--seed"));c.seed_set=true;}else if(a=="--iters"&&loop)c.iters=std::stoi(val("--iters"));else if(a=="--pcg-tol")c.solver.pcg_tol=std::stod(val("--pcg-tol"));else if(a=="--pcg-maxit")c.solver.pcg_maxit=std::stoi(val("--pcg-maxit"));else if(a=="--no-fallback")c.solver.fallback_direct=false;else if(a=="--no-template-parallel")c.solver.parallel_templates=false;else if(a=="--no-backend-parallel")c.solver.parallel_backend_retries=false;else if(a=="--outer-parallel")c.solver.parallel_templates=true;else throw std::runtime_error("unknown option "+a);}if(!data_dir_set){if(const char*e=std::getenv("AXYB_TEMPLATE_DIR")){c.solver.template_dir=e;}else{std::vector<std::string>candidates={join_path(executable_dir(argc?argv[0]:nullptr),"templates"),"templates","data/templates","../data/templates"};for(const auto&d:candidates)if(has_templates(d)){c.solver.template_dir=d;break;}}}return c;}
inline unsigned long long choose_seed(CommonCli&c){if(c.seed_set)return c.seed;std::random_device rd;c.seed=(static_cast<unsigned long long>(rd())<<32u)^static_cast<unsigned long long>(rd());return c.seed;}
}
